//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopNotification.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopNotification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Desktop Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseWindowCategory {
            get {
                return ResourceManager.GetString("CloseWindowCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Notification Window on Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseWindowDescription {
            get {
                return ResourceManager.GetString("CloseWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Notification Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseWindowDisplayName {
            get {
                return ResourceManager.GetString("CloseWindowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Color Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorThemeDescription {
            get {
                return ResourceManager.GetString("ColorThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorThemeDisplayName {
            get {
                return ResourceManager.GetString("ColorThemeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DesignCategory {
            get {
                return ResourceManager.GetString("DesignCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSizeDisplayName {
            get {
                return ResourceManager.GetString("FontSizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UiPath-DesktopNotification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCategory {
            get {
                return ResourceManager.GetString("InputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDescription {
            get {
                return ResourceManager.GetString("MessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDisplayName {
            get {
                return ResourceManager.GetString("MessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Percentage (0-100) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressPercentageDescription {
            get {
                return ResourceManager.GetString("ProgressPercentageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressPercentageDisplayName {
            get {
                return ResourceManager.GetString("ProgressPercentageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowMessageCategory {
            get {
                return ResourceManager.GetString("ShowMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Mesage Window on Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowMessageDescription {
            get {
                return ResourceManager.GetString("ShowMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Mesage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowMessageDisplayName {
            get {
                return ResourceManager.GetString("ShowMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowProgressBarCategory {
            get {
                return ResourceManager.GetString("ShowProgressBarCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Progress Bar and Mesage Window on Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowProgressBarDescription {
            get {
                return ResourceManager.GetString("ShowProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show ProgressBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowProgressBarDisplayName {
            get {
                return ResourceManager.GetString("ShowProgressBarDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleDisplayName {
            get {
                return ResourceManager.GetString("TitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Display Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowPositionDescription {
            get {
                return ResourceManager.GetString("WindowPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowPositionDisplayName {
            get {
                return ResourceManager.GetString("WindowPositionDisplayName", resourceCulture);
            }
        }
    }
}
